linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - misspell
    - goimports
    - revive
    - gosec

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false

run:
  deadline: 5m
  skip-dirs:
    - vendor
    - api/proto

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck 