-- +migrate Up
CREATE TABLE IF NOT EXISTS whitelist (
    id SERIAL PRIMARY KEY,
    subnet CIDR NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blacklist (
    id SERIAL PRIMARY KEY,
    subnet CIDR NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS whitelist;
DROP TABLE IF EXISTS blacklist;
