env: "ci"

limiters:
  login:
    maxAttemptsPerMinute: 10   # N
    cleanupInterval: 1m        # how often to clean up the bucket
    ttl: 10m                   # max lifetime for the bucket if it's not used
  password:
    maxAttemptsPerMinute: 100  # M
    cleanupInterval: 1m
    ttl: 10m
  ip:
    maxAttemptsPerMinute: 1000 # K
    cleanupInterval: 1m
    ttl: 10m

grpc:
  port: "13013"

postgres:
  database: anti-brute-force
  username: postgres
  password: postgres
  host: postgres
  port: "5432"
  sslmode: disable 